/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Student creates an invite code for their parent */
        post: operations["create_invite_auth_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parent redeems the invite code, linking the two accounts */
        post: operations["link_accounts_auth_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who am I: role, linked pair, progress and consent flags */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your saved profile */
        get: operations["read_profile_profile_get"];
        /** Save your profile: a parent's finances and hopes, or a student's preferences */
        put: operations["save_profile_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Career domains, for the parent's top-3 picker */
        get: operations["list_domains_domains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The question set for students or parents */
        get: operations["get_questions_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save your answers (batch; re-sending a question overwrites it)
         * @description Mock mode stores nothing, so "answered" counts only the questions in this request.
         */
        post: operations["save_responses_responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agree (or stop agreeing) to the parent-student comparison */
        post: operations["give_consent_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the whole pipeline for a linked pair and return the roadmap
         * @description Mock mode returns the saved demo result. Custom weights are validated
         *     but only change the ranking once feat/be-E1-E2-roadmap-endpoint lands.
         */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A saved roadmap */
        get: operations["get_result_results__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plain-language explanation of one career in a result */
        post: operations["explain_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/careers/{career_id}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demand and salary by region for one career */
        get: operations["career_market_careers__career_id__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load the demo family and return its result id (only when DEMO_ENABLED=true; no login) */
        post: operations["run_demo_demo_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
            /**
             * @description Must sum to 1, otherwise INVALID_WEIGHTS
             * @default {
             *       "fit": 0.45,
             *       "finance": 0.3,
             *       "market": 0.25
             *     }
             */
            weights: components["schemas"]["Weights"];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            weights: components["schemas"]["Weights"];
            conflict: components["schemas"]["Conflict"];
            swot: components["schemas"]["Swot"];
            /** Traits */
            traits: components["schemas"]["Trait"][];
            /**
             * Domain Scores
             * @description Best fit first
             */
            domain_scores: components["schemas"]["DomainScore"][];
            /**
             * Roadmap
             * @description Viable paths first, by final score; filled with non-viable ones (finance.viable = false) when fewer than 5 are viable
             */
            roadmap: components["schemas"]["RoadmapItem"][];
            /**
             * Rejected
             * @description Non-viable careers that did not make the roadmap
             */
            rejected: components["schemas"]["RejectedCareer"][];
        };
        /** Answer */
        Answer: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Value
             * @description 1 = strongly disagree ... 5 = strongly agree
             */
            value: number;
        };
        /** AnswerOption */
        AnswerOption: {
            /** Value */
            value: number;
            /** Label */
            label: string;
        };
        /** CareerMarket */
        CareerMarket: {
            /**
             * Career Id
             * Format: uuid
             */
            career_id: string;
            /** Career */
            career: string;
            /** Domain */
            domain: string;
            national: components["schemas"]["RegionMarket"] | null;
            /** Regions */
            regions: components["schemas"]["RegionMarket"][];
        };
        /** College */
        College: {
            /** Name */
            name: string;
            /**
             * Annual Fee
             * @description Whole rupees
             */
            annual_fee: number;
        };
        /** Conflict */
        Conflict: {
            /**
             * Index
             * @description 100 x the mean of the four gaps
             */
            index: number;
            /**
             * Label
             * @description under 30 low, 30-60 moderate, above 60 high
             * @enum {string}
             */
            label: "low" | "moderate" | "high";
            /**
             * Top Gaps
             * @description The three largest gaps, largest first
             */
            top_gaps: components["schemas"]["Gap"][];
            /**
             * Gaps
             * @description All four gaps, largest first
             */
            gaps: components["schemas"]["Gap"][];
        };
        /** ConsentRequest */
        ConsentRequest: {
            /**
             * Agree
             * @description true to allow the parent-student comparison, false to withdraw
             */
            agree: boolean;
        };
        /** ConsentResponse */
        ConsentResponse: {
            /** Consented */
            consented: boolean;
            /** Consented At */
            consented_at: string | null;
            /**
             * Both Consented
             * @description True when the linked partner has agreed too
             */
            both_consented: boolean;
        };
        /** DemoRunResponse */
        DemoRunResponse: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
        };
        /**
         * Dimension
         * @description The 13 trait dimensions. Question dimensions and careers.trait_weights keys use exactly these values.
         * @enum {string}
         */
        Dimension: "logical" | "numerical" | "verbal" | "spatial" | "creative" | "realistic" | "investigative" | "artistic" | "social" | "enterprising" | "conventional" | "analytical" | "structured";
        /** Domain */
        Domain: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /**
         * DomainScore
         * @description Mean of the scores of the careers in this domain.
         */
        DomainScore: {
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /** Domain */
            domain: string;
            /**
             * Fit
             * @description 0..1
             */
            fit: number;
            /**
             * Aptitude
             * @description 0..1
             */
            aptitude: number;
            /**
             * Interest
             * @description 0..1
             */
            interest: number;
            /**
             * Cognitive
             * @description 0..1
             */
            cognitive: number;
        };
        /** EducationPath */
        EducationPath: {
            /** Education */
            education: string;
            /** Exams */
            exams: string[];
            /**
             * Colleges
             * @description The finance check uses the first college
             */
            colleges: components["schemas"]["College"][];
        };
        /**
         * ErrorBody
         * @description Every error response has this shape.
         */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "ASSESSMENT_INCOMPLETE" | "CONSENT_REQUIRED" | "INVALID_WEIGHTS" | "VALIDATION_ERROR" | "INTERNAL_ERROR" | "NOT_IMPLEMENTED" | "UPSTREAM_UNAVAILABLE";
        /** ErrorDetail */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Career Id
             * Format: uuid
             */
            career_id: string;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /**
             * Career Id
             * Format: uuid
             */
            career_id: string;
            /**
             * Text
             * @description Under 150 words, built only from the numbers in the result
             */
            text: string;
            /**
             * Source
             * @description Lets the UI tag AI-written vs template text
             * @enum {string}
             */
            source: "cache" | "gemini" | "template";
        };
        /** FinanceCheck */
        FinanceCheck: {
            /** Viable */
            viable: boolean;
            /**
             * Total Cost
             * @description (annual fee + living cost) x duration - matched scholarship
             */
            total_cost: number;
            /**
             * Capacity
             * @description What the family can pay over the course without a loan
             */
            capacity: number;
            /**
             * Loan Needed
             * @description max(0, total_cost - capacity)
             */
            loan_needed: number;
            /**
             * Starting Salary
             * @description Whole rupees
             */
            starting_salary: number;
            /**
             * Breakeven Years
             * @description total_cost / (starting salary - yearly living costs)
             */
            breakeven_years: number;
            /** Duration Years */
            duration_years: number;
            /**
             * Reasons
             * @description Why the path is not viable; empty when viable
             */
            reasons: components["schemas"]["FinanceReason"][];
        };
        /**
         * FinanceParts
         * @description finance = 0.5 x capacity_ratio + 0.3 x loan + 0.2 x payback
         */
        FinanceParts: {
            /**
             * Capacity Ratio
             * @description min(1, capacity / total_cost)
             */
            capacity_ratio: number;
            /**
             * Loan
             * @description 1 when the loan is within the family's limit, lower the further above it
             */
            loan: number;
            /**
             * Payback
             * @description 1 - breakeven / (2 x the family's tolerance), clamped to 0..1
             */
            payback: number;
        };
        /**
         * FinanceReason
         * @enum {string}
         */
        FinanceReason: "LOAN_EXCEEDS_LIMIT" | "BREAKEVEN_TOO_LONG" | "COST_EXCEEDS_CAPACITY";
        /**
         * FitParts
         * @description fit = 0.5 x aptitude + 0.3 x interest + 0.2 x cognitive
         */
        FitParts: {
            /**
             * Aptitude
             * @description 0..1
             */
            aptitude: number;
            /**
             * Interest
             * @description 0..1
             */
            interest: number;
            /**
             * Cognitive
             * @description 0..1
             */
            cognitive: number;
        };
        /** Gap */
        Gap: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "domain" | "risk" | "location" | "budget";
            /**
             * Gap
             * @description 0 = agree ... 1 = fully disagree
             */
            gap: number;
            /** Text */
            text: string;
            /**
             * Student Value
             * @description The student's side, for display
             */
            student_value: string | null;
            /**
             * Parent Value
             * @description The parent's side, for display
             */
            parent_value: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @description 'skipped' until the database check lands
             * @enum {string}
             */
            database: "ok" | "unavailable" | "skipped";
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            /** Version */
            version: string;
        };
        /**
         * IndianState
         * @description States and union territories, spelled exactly like this everywhere (profiles, market data).
         * @enum {string}
         */
        IndianState: "Andhra Pradesh" | "Arunachal Pradesh" | "Assam" | "Bihar" | "Chhattisgarh" | "Goa" | "Gujarat" | "Haryana" | "Himachal Pradesh" | "Jharkhand" | "Karnataka" | "Kerala" | "Madhya Pradesh" | "Maharashtra" | "Manipur" | "Meghalaya" | "Mizoram" | "Nagaland" | "Odisha" | "Punjab" | "Rajasthan" | "Sikkim" | "Tamil Nadu" | "Telangana" | "Tripura" | "Uttar Pradesh" | "Uttarakhand" | "West Bengal" | "Andaman and Nicobar Islands" | "Chandigarh" | "Dadra and Nagar Haveli and Daman and Diu" | "Delhi" | "Jammu and Kashmir" | "Ladakh" | "Lakshadweep" | "Puducherry";
        /** InviteResponse */
        InviteResponse: {
            /**
             * Invite Code
             * @description Short code the student shares with their parent; single use
             */
            invite_code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LinkRequest */
        LinkRequest: {
            /** Invite Code */
            invite_code: string;
        };
        /** LinkResponse */
        LinkResponse: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
            /**
             * Linked At
             * Format: date-time
             */
            linked_at: string;
        };
        /**
         * MarketParts
         * @description market = 0.5 x demand + 0.3 x growth + 0.2 x salary_percentile, each min-max scaled across careers
         */
        MarketParts: {
            /**
             * Demand
             * @description 0..1
             */
            demand: number;
            /**
             * Growth
             * @description 0..1
             */
            growth: number;
            /**
             * Salary Percentile
             * @description 0..1
             */
            salary_percentile: number;
        };
        /** MatchedScholarship */
        MatchedScholarship: {
            /** Name */
            name: string;
            /**
             * Amount
             * @description Whole rupees
             */
            amount: number;
            /** Deadline */
            deadline: string | null;
            /**
             * Matched Rule
             * @description The eligibility rule the family met, e.g. 'percentage >= 85'
             */
            matched_rule: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            role: components["schemas"]["Role"];
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** @description Null until the parent redeems the invite code */
            pair: components["schemas"]["Pair"] | null;
            progress: components["schemas"]["Progress"];
            /** Consented */
            consented: boolean;
            /** @description Null until linked */
            partner: components["schemas"]["PartnerStatus"] | null;
            /** Latest Result Id */
            latest_result_id: string | null;
        };
        /** Pair */
        Pair: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
        };
        /** ParentProfile */
        ParentProfile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "parent";
            /**
             * Annual Education Budget
             * @description What the family can spend on education each year
             */
            annual_education_budget: number;
            /**
             * Savings
             * @description Savings set aside for education
             */
            savings: number;
            /**
             * Max Loan
             * @description Largest education loan the family will take
             */
            max_loan: number;
            /**
             * Annual Income
             * @description Optional; used only to match scholarship income limits
             */
            annual_income?: number | null;
            /**
             * Risk Appetite
             * @description 1 = avoids risk ... 5 = very comfortable with risk
             */
            risk_appetite: number;
            /**
             * Breakeven Tolerance Years
             * @description Years of salary the family accepts to recover the cost
             */
            breakeven_tolerance_years: number;
            preferred_state: components["schemas"]["IndianState"];
            /** Open To Abroad */
            open_to_abroad: boolean;
            /**
             * Top Domain Ids
             * @description The parent's top 3 domains (ids from GET /domains), first choice first
             */
            top_domain_ids: string[];
        };
        /**
         * PartnerStatus
         * @description Only status flags about the linked partner; never their answers.
         */
        PartnerStatus: {
            role: components["schemas"]["Role"];
            /**
             * Full Name
             * @description So the UI can say who is linked; null if they gave no name
             */
            full_name: string | null;
            /** Assessment Complete */
            assessment_complete: boolean;
            /** Consented */
            consented: boolean;
        };
        /** Progress */
        Progress: {
            /** Questions Answered */
            questions_answered: number;
            /**
             * Questions Required
             * @description 0 for parents: their assessment is the profile form
             */
            questions_required: number;
            /** Profile Complete */
            profile_complete: boolean;
            /**
             * Assessment Complete
             * @description All required questions answered and the profile saved
             */
            assessment_complete: boolean;
        };
        /**
         * Question
         * @description One 1-5 statement. Whether it is reverse-scored stays on the server.
         */
        Question: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @description likert: rate a statement from 1 to 5. choice: pick the one correct option; the server grades it
             * @enum {string}
             */
            kind: "likert" | "choice";
            group: components["schemas"]["TraitGroup"];
            dimension: components["schemas"]["Dimension"];
            /** Text */
            text: string;
            /** Options */
            options: components["schemas"]["AnswerOption"][];
            /** Required */
            required: boolean;
        };
        /** QuestionSet */
        QuestionSet: {
            audience: components["schemas"]["Role"];
            /**
             * Questions
             * @description In display order. Empty for parents: their assessment is the profile form (PUT /profile).
             */
            questions: components["schemas"]["Question"][];
        };
        /**
         * RegionMarket
         * @description Market figures for one career in one region (or "India" for the national figure).
         */
        RegionMarket: {
            /** Region */
            region: components["schemas"]["IndianState"] | "India";
            /**
             * Demand Index
             * @description 0..1
             */
            demand_index: number;
            /**
             * Growth Rate
             * @description Yearly growth in percent, as published by the source
             */
            growth_rate: number | null;
            /** Median Salary */
            median_salary: number | null;
            /**
             * Entry Salary
             * @description Typical starting salary for a fresher
             */
            entry_salary: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Source */
            source: string;
            /**
             * Data Quality
             * @description 'estimated' when the figure is an estimate or the national figure stands in for missing regional data
             * @enum {string}
             */
            data_quality: "sourced" | "estimated";
        };
        /** RejectedCareer */
        RejectedCareer: {
            /**
             * Career Id
             * Format: uuid
             */
            career_id: string;
            /** Career */
            career: string;
            /** Reasons */
            reasons: components["schemas"]["FinanceReason"][];
            /** Cheaper Alternative */
            cheaper_alternative: string | null;
        };
        /** ResponsesBatch */
        ResponsesBatch: {
            /** Answers */
            answers: components["schemas"]["Answer"][];
        };
        /** ResponsesSaved */
        ResponsesSaved: {
            /**
             * Saved
             * @description Questions stored by this request; re-sending a question overwrites it
             */
            saved: number;
            /**
             * Answered
             * @description Questions this user has answered so far
             */
            answered: number;
            /** Required */
            required: number;
            /** Complete */
            complete: boolean;
        };
        /** RoadmapItem */
        RoadmapItem: {
            /** Rank */
            rank: number;
            /**
             * Career Id
             * Format: uuid
             */
            career_id: string;
            /** Career */
            career: string;
            /** Domain */
            domain: string;
            scores: components["schemas"]["Scores"];
            finance: components["schemas"]["FinanceCheck"];
            market: components["schemas"]["RegionMarket"];
            path: components["schemas"]["EducationPath"];
            /** Scholarships */
            scholarships: components["schemas"]["MatchedScholarship"][];
            /** Cheaper Alternative */
            cheaper_alternative: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "student" | "parent";
        /** Scores */
        Scores: {
            /**
             * Fit
             * @description 0..1
             */
            fit: number;
            /**
             * Finance
             * @description 0..1
             */
            finance: number;
            /**
             * Market
             * @description 0..1
             */
            market: number;
            /**
             * Final
             * @description weights.fit x fit + weights.finance x finance + weights.market x market
             */
            final: number;
            /**
             * Final 100
             * @description 0..100, for display
             */
            final_100: number;
            fit_parts: components["schemas"]["FitParts"];
            finance_parts: components["schemas"]["FinanceParts"];
            market_parts: components["schemas"]["MarketParts"];
        };
        /** StudentProfile */
        StudentProfile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "student";
            /**
             * Risk Appetite
             * @description 1 = avoids risk ... 5 = very comfortable with risk
             */
            risk_appetite: number;
            /** @description Where the student would like to study and work */
            preferred_state: components["schemas"]["IndianState"];
            /** Open To Abroad */
            open_to_abroad: boolean;
            /** @description State of residence; used for state scholarships */
            home_state: components["schemas"]["IndianState"];
            /**
             * Category
             * @description Optional; used only for scholarship rules
             */
            category?: ("general" | "obc" | "sc" | "st" | "ews") | null;
            /**
             * Percentage
             * @description Latest board exam percentage; optional, used for merit scholarships
             */
            percentage?: number | null;
            /**
             * Gender
             * @description Optional; some scholarships are for girls only
             */
            gender?: ("female" | "male" | "other") | null;
        };
        /** Swot */
        Swot: {
            /** Strengths */
            strengths: components["schemas"]["SwotItem"][];
            /** Weaknesses */
            weaknesses: components["schemas"]["SwotItem"][];
            /** Opportunities */
            opportunities: components["schemas"]["SwotItem"][];
            /** Threats */
            threats: components["schemas"]["SwotItem"][];
        };
        /** SwotItem */
        SwotItem: {
            /** Text */
            text: string;
            /**
             * Value
             * @description The number that produced this item: a trait score, demand score, years or rupees
             */
            value: number;
        };
        /** Trait */
        Trait: {
            dimension: components["schemas"]["Dimension"];
            group: components["schemas"]["TraitGroup"];
            /**
             * Value
             * @description Null when the student answered no questions for this dimension
             */
            value: number | null;
        };
        /**
         * TraitGroup
         * @enum {string}
         */
        TraitGroup: "aptitude" | "interest" | "cognitive";
        /**
         * Weights
         * @description Weights for the final ranking R = fit*S + finance*F + market*M (backend guide, section 4, step 5).
         */
        Weights: {
            /** Fit */
            fit: number;
            /** Finance */
            finance: number;
            /** Market */
            market: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description UPSTREAM_UNAVAILABLE: the database cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_invite_auth_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    link_accounts_auth_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentProfile"] | components["schemas"]["StudentProfile"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    save_profile_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParentProfile"] | components["schemas"]["StudentProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentProfile"] | components["schemas"]["StudentProfile"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_domains_domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_questions_questions_get: {
        parameters: {
            query: {
                audience: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSet"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    save_responses_responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponsesBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsesSaved"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    give_consent_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description ASSESSMENT_INCOMPLETE or CONSENT_REQUIRED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_result_results__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    explain_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description FORBIDDEN: signed in, but not allowed to do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    career_market_careers__career_id__market_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                career_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerMarket"];
                };
            };
            /** @description UNAUTHENTICATED: missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_WEIGHTS: details.fields lists what is wrong */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    run_demo_demo_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoRunResponse"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description INTERNAL_ERROR: a bug on our side; quote the X-Request-ID header */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
