-- =============================================================================
-- Seed 03: each career's trait weights, GENERATED by db/scripts/onet_trait_weights.py. Do not edit;
-- change the script's mapping and regenerate.
--
-- Source: O*NET 31.0 Database, U.S. Department of Labor, Employment and Training Administration
-- (https://www.onetcenter.org/database.html), CC BY 4.0. Abilities (importance), Career Interest Types
-- (occupational interests) and Work Styles (impact), weighted by how far each career is above the
-- average occupation. The O*NET occupation used for each career is noted on its line.
-- =============================================================================

-- Software Engineer: O*NET 15-1252.00 Software Developers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.49, "logical": 0.32, "numerical": 0.13, "verbal": 0.06}, "interest": {"investigative": 0.64, "conventional": 0.26, "artistic": 0.1}, "cognitive": {"analytical": 0.92, "structured": 0.08}}' WHERE name = 'Software Engineer';
-- Data Scientist: O*NET 15-2051.00 Data Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.43, "logical": 0.23, "spatial": 0.18, "creative": 0.11, "verbal": 0.05}, "interest": {"investigative": 0.7, "conventional": 0.17, "artistic": 0.13}, "cognitive": {"analytical": 0.96, "structured": 0.04}}' WHERE name = 'Data Scientist';
-- Mechanical Engineer: O*NET 17-2141.00 Mechanical Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.42, "creative": 0.2, "logical": 0.16, "spatial": 0.13, "verbal": 0.09}, "interest": {"realistic": 0.46, "investigative": 0.44, "conventional": 0.08, "artistic": 0.02}, "cognitive": {"analytical": 0.76, "structured": 0.24}}' WHERE name = 'Mechanical Engineer';
-- Robotics Engineer: O*NET 17-2199.08 Robotics Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.3, "creative": 0.28, "logical": 0.17, "spatial": 0.17, "verbal": 0.08}, "interest": {"investigative": 0.58, "realistic": 0.42}, "cognitive": {"analytical": 0.8, "structured": 0.2}}' WHERE name = 'Robotics Engineer';
-- Medical Doctor (MBBS): O*NET 29-1215.00 Family Medicine Physicians
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.54, "spatial": 0.18, "numerical": 0.13, "creative": 0.09, "logical": 0.06}, "interest": {"social": 0.55, "investigative": 0.45}, "cognitive": {"analytical": 0.64, "structured": 0.36}}' WHERE name = 'Medical Doctor (MBBS)';
-- Biotechnology Researcher: O*NET 19-1021.00 Biochemists and Biophysicists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.3, "creative": 0.22, "logical": 0.19, "spatial": 0.15, "verbal": 0.14}, "interest": {"investigative": 0.75, "artistic": 0.14, "realistic": 0.11}, "cognitive": {"analytical": 0.89, "structured": 0.11}}' WHERE name = 'Biotechnology Researcher';
-- Chartered Accountant (CA): O*NET 13-2011.00 Accountants and Auditors
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.59, "spatial": 0.21, "logical": 0.12, "verbal": 0.07, "creative": 0.01}, "interest": {"conventional": 0.66, "enterprising": 0.28, "investigative": 0.06}, "cognitive": {"analytical": 0.61, "structured": 0.39}}' WHERE name = 'Chartered Accountant (CA)';
-- Investment Banker: O*NET 41-3031.00 Securities, Commodities, and Financial Services Sales Agents
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.56, "creative": 0.21, "verbal": 0.13, "spatial": 0.1}, "interest": {"enterprising": 0.79, "conventional": 0.18, "social": 0.03}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Investment Banker';
-- UX/UI Designer: O*NET 15-1255.00 Web and Digital Interface Designers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.82, "spatial": 0.18}, "interest": {"artistic": 0.58, "investigative": 0.35, "enterprising": 0.07}, "cognitive": {"analytical": 1.0}}' WHERE name = 'UX/UI Designer';
-- Educational Policy Specialist: O*NET 25-9031.00 Instructional Coordinators
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.33, "verbal": 0.25, "logical": 0.17, "numerical": 0.16, "spatial": 0.09}, "interest": {"social": 0.46, "artistic": 0.23, "enterprising": 0.21, "investigative": 0.1}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Educational Policy Specialist';
-- Agricultural Scientist: O*NET 19-1013.00 Soil and Plant Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.29, "logical": 0.24, "numerical": 0.19, "spatial": 0.15, "verbal": 0.13}, "interest": {"investigative": 0.62, "realistic": 0.35, "artistic": 0.03}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Agricultural Scientist';
-- Corporate Lawyer: O*NET 23-1011.00 Lawyers
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.39, "creative": 0.32, "logical": 0.2, "spatial": 0.09}, "interest": {"enterprising": 0.57, "investigative": 0.21, "social": 0.11, "artistic": 0.1, "conventional": 0.01}, "cognitive": {"analytical": 0.78, "structured": 0.22}}' WHERE name = 'Corporate Lawyer';
-- Armed Forces Officer (NDA): O*NET 33-1012.00 First-Line Supervisors of Police and Detectives
UPDATE careers SET trait_weights = '{"aptitude": {"spatial": 0.31, "verbal": 0.3, "logical": 0.25, "creative": 0.14}, "interest": {"enterprising": 0.75, "social": 0.15, "conventional": 0.1}, "cognitive": {"structured": 1.0}}' WHERE name = 'Armed Forces Officer (NDA)';
