-- =============================================================================
-- Seed 03: each career's trait weights, GENERATED by db/scripts/onet_trait_weights.py. Do not edit;
-- change the onet column in db/data/careers.csv and regenerate.
--
-- Source: O*NET 31.0 Database, U.S. Department of Labor, Employment and Training Administration
-- (https://www.onetcenter.org/database.html), CC BY 4.0. Abilities (importance), Career Interest Types
-- (occupational interests) and Work Styles (impact), weighted by how far each career is above the
-- average occupation. The O*NET occupation used for each career is noted on its line.
-- =============================================================================

-- Software Engineer: O*NET 15-1252.00 Software Developers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.49, "logical": 0.32, "numerical": 0.13, "verbal": 0.06}, "interest": {"investigative": 0.64, "conventional": 0.26, "artistic": 0.1}, "cognitive": {"analytical": 0.92, "structured": 0.08}}' WHERE name = 'Software Engineer';
-- Data Scientist: O*NET 15-2051.00 Data Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.43, "logical": 0.23, "spatial": 0.18, "creative": 0.11, "verbal": 0.05}, "interest": {"investigative": 0.7, "conventional": 0.17, "artistic": 0.13}, "cognitive": {"analytical": 0.96, "structured": 0.04}}' WHERE name = 'Data Scientist';
-- AI / ML Engineer: O*NET 15-1221.00 Computer and Information Research Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.33, "numerical": 0.28, "logical": 0.2, "verbal": 0.1, "spatial": 0.09}, "interest": {"investigative": 0.73, "artistic": 0.21, "conventional": 0.06}, "cognitive": {"analytical": 1.0}}' WHERE name = 'AI / ML Engineer';
-- Cybersecurity Analyst: O*NET 15-1212.00 Information Security Analysts
UPDATE careers SET trait_weights = '{"aptitude": {"logical": 0.37, "spatial": 0.35, "verbal": 0.21, "creative": 0.07}, "interest": {"investigative": 0.56, "conventional": 0.43, "enterprising": 0.01}, "cognitive": {"analytical": 0.66, "structured": 0.34}}' WHERE name = 'Cybersecurity Analyst';
-- Electronics & Telecom Engineer: O*NET 15-1241.01 Telecommunications Engineering Specialists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.55, "verbal": 0.27, "creative": 0.15, "logical": 0.03}, "interest": {"investigative": 0.58, "conventional": 0.27, "enterprising": 0.15}, "cognitive": {"analytical": 0.82, "structured": 0.18}}' WHERE name = 'Electronics & Telecom Engineer';
-- VLSI / Chip Design Engineer: O*NET 17-2061.00 Computer Hardware Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.29, "logical": 0.28, "creative": 0.27, "verbal": 0.16}, "interest": {"investigative": 0.53, "realistic": 0.27, "conventional": 0.2}, "cognitive": {"analytical": 0.92, "structured": 0.08}}' WHERE name = 'VLSI / Chip Design Engineer';
-- Embedded Systems Engineer: O*NET 17-2072.00 Electronics Engineers, Except Computer
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.35, "creative": 0.21, "logical": 0.19, "spatial": 0.13, "verbal": 0.12}, "interest": {"investigative": 0.56, "realistic": 0.38, "conventional": 0.04, "artistic": 0.02}, "cognitive": {"analytical": 0.8, "structured": 0.2}}' WHERE name = 'Embedded Systems Engineer';
-- Electrical Engineer: O*NET 17-2071.00 Electrical Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.39, "logical": 0.26, "verbal": 0.19, "creative": 0.16}, "interest": {"investigative": 0.56, "realistic": 0.39, "artistic": 0.05}, "cognitive": {"analytical": 0.74, "structured": 0.26}}' WHERE name = 'Electrical Engineer';
-- O*NET has no instrumentation engineer; Mechatronics Engineers covers control and automation systems.
-- Instrumentation & Control Engineer: O*NET 17-2199.05 Mechatronics Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.3, "numerical": 0.25, "verbal": 0.18, "logical": 0.15, "spatial": 0.12}, "interest": {"investigative": 0.53, "realistic": 0.27, "artistic": 0.12, "conventional": 0.08}, "cognitive": {"analytical": 0.83, "structured": 0.17}}' WHERE name = 'Instrumentation & Control Engineer';
-- Mechanical Engineer: O*NET 17-2141.00 Mechanical Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.42, "creative": 0.2, "logical": 0.16, "spatial": 0.13, "verbal": 0.09}, "interest": {"realistic": 0.46, "investigative": 0.44, "conventional": 0.08, "artistic": 0.02}, "cognitive": {"analytical": 0.76, "structured": 0.24}}' WHERE name = 'Mechanical Engineer';
-- Robotics Engineer: O*NET 17-2199.08 Robotics Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.3, "creative": 0.28, "logical": 0.17, "spatial": 0.17, "verbal": 0.08}, "interest": {"investigative": 0.58, "realistic": 0.42}, "cognitive": {"analytical": 0.8, "structured": 0.2}}' WHERE name = 'Robotics Engineer';
-- Automobile / EV Engineer: O*NET 17-2141.02 Automotive Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.41, "creative": 0.32, "logical": 0.14, "verbal": 0.1, "spatial": 0.03}, "interest": {"investigative": 0.51, "realistic": 0.35, "artistic": 0.14}, "cognitive": {"analytical": 0.89, "structured": 0.11}}' WHERE name = 'Automobile / EV Engineer';
-- Aerospace Engineer: O*NET 17-2011.00 Aerospace Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.36, "creative": 0.23, "logical": 0.22, "verbal": 0.13, "spatial": 0.06}, "interest": {"investigative": 0.64, "realistic": 0.26, "artistic": 0.1}, "cognitive": {"analytical": 0.69, "structured": 0.31}}' WHERE name = 'Aerospace Engineer';
-- Civil Engineer: O*NET 17-2051.00 Civil Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.38, "creative": 0.18, "spatial": 0.17, "logical": 0.16, "verbal": 0.11}, "interest": {"realistic": 0.46, "investigative": 0.45, "artistic": 0.07, "conventional": 0.02}, "cognitive": {"analytical": 0.74, "structured": 0.26}}' WHERE name = 'Civil Engineer';
-- Chemical Engineer: O*NET 17-2041.00 Chemical Engineers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.38, "logical": 0.21, "creative": 0.19, "spatial": 0.17, "verbal": 0.05}, "interest": {"investigative": 0.59, "realistic": 0.41}, "cognitive": {"analytical": 0.73, "structured": 0.27}}' WHERE name = 'Chemical Engineer';
-- Quantitative Analyst: O*NET 13-2099.01 Financial Quantitative Analysts
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.62, "creative": 0.19, "logical": 0.09, "verbal": 0.09, "spatial": 0.01}, "interest": {"investigative": 0.64, "conventional": 0.24, "enterprising": 0.12}, "cognitive": {"analytical": 0.75, "structured": 0.25}}' WHERE name = 'Quantitative Analyst';
-- Astrophysicist / Astronomer: O*NET 19-2011.00 Astronomers
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.38, "creative": 0.22, "logical": 0.14, "spatial": 0.14, "verbal": 0.12}, "interest": {"investigative": 0.66, "artistic": 0.25, "realistic": 0.09}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Astrophysicist / Astronomer';
-- Physicist: O*NET 19-2012.00 Physicists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.36, "creative": 0.23, "logical": 0.14, "spatial": 0.14, "verbal": 0.13}, "interest": {"investigative": 0.72, "artistic": 0.16, "realistic": 0.07, "conventional": 0.05}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Physicist';
-- Mathematician / Statistician: O*NET 15-2041.00 Statisticians
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.6, "logical": 0.13, "verbal": 0.12, "creative": 0.08, "spatial": 0.07}, "interest": {"investigative": 0.68, "conventional": 0.32}, "cognitive": {"analytical": 0.83, "structured": 0.17}}' WHERE name = 'Mathematician / Statistician';
-- Actuary: O*NET 15-2011.00 Actuaries
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.59, "logical": 0.18, "verbal": 0.11, "spatial": 0.07, "creative": 0.05}, "interest": {"conventional": 0.53, "investigative": 0.32, "enterprising": 0.15}, "cognitive": {"analytical": 0.71, "structured": 0.29}}' WHERE name = 'Actuary';
-- Biotechnology Researcher: O*NET 19-1021.00 Biochemists and Biophysicists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.3, "creative": 0.22, "logical": 0.19, "spatial": 0.15, "verbal": 0.14}, "interest": {"investigative": 0.75, "artistic": 0.14, "realistic": 0.11}, "cognitive": {"analytical": 0.89, "structured": 0.11}}' WHERE name = 'Biotechnology Researcher';
-- Microbiologist: O*NET 19-1022.00 Microbiologists
UPDATE careers SET trait_weights = '{"aptitude": {"logical": 0.28, "creative": 0.22, "spatial": 0.2, "verbal": 0.19, "numerical": 0.11}, "interest": {"investigative": 0.84, "realistic": 0.16}, "cognitive": {"analytical": 0.79, "structured": 0.21}}' WHERE name = 'Microbiologist';
-- Agricultural Scientist: O*NET 19-1013.00 Soil and Plant Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.29, "logical": 0.24, "numerical": 0.19, "spatial": 0.15, "verbal": 0.13}, "interest": {"investigative": 0.62, "realistic": 0.35, "artistic": 0.03}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Agricultural Scientist';
-- Forensic Scientist: O*NET 19-4092.00 Forensic Science Technicians
UPDATE careers SET trait_weights = '{"aptitude": {"spatial": 0.45, "logical": 0.25, "verbal": 0.18, "creative": 0.08, "numerical": 0.04}, "interest": {"investigative": 0.71, "realistic": 0.17, "conventional": 0.12}, "cognitive": {"analytical": 0.64, "structured": 0.36}}' WHERE name = 'Forensic Scientist';
-- Environmental Scientist: O*NET 19-2041.00 Environmental Scientists and Specialists, Including Health
UPDATE careers SET trait_weights = '{"aptitude": {"logical": 0.28, "numerical": 0.23, "verbal": 0.21, "spatial": 0.18, "creative": 0.1}, "interest": {"investigative": 0.95, "realistic": 0.05}, "cognitive": {"analytical": 0.84, "structured": 0.16}}' WHERE name = 'Environmental Scientist';
-- Medical Doctor (MBBS): O*NET 29-1215.00 Family Medicine Physicians
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.54, "spatial": 0.18, "numerical": 0.13, "creative": 0.09, "logical": 0.06}, "interest": {"social": 0.55, "investigative": 0.45}, "cognitive": {"analytical": 0.64, "structured": 0.36}}' WHERE name = 'Medical Doctor (MBBS)';
-- Dentist: O*NET 29-1021.00 Dentists, General
UPDATE careers SET trait_weights = '{"aptitude": {"logical": 0.31, "spatial": 0.28, "creative": 0.15, "numerical": 0.14, "verbal": 0.12}, "interest": {"investigative": 0.5, "social": 0.35, "realistic": 0.15}, "cognitive": {"analytical": 0.62, "structured": 0.38}}' WHERE name = 'Dentist';
-- Pharmacist: O*NET 29-1051.00 Pharmacists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.35, "logical": 0.34, "verbal": 0.25, "spatial": 0.06}, "interest": {"investigative": 0.54, "social": 0.45, "conventional": 0.01}, "cognitive": {"analytical": 0.58, "structured": 0.42}}' WHERE name = 'Pharmacist';
-- Nurse: O*NET 29-1141.00 Registered Nurses
UPDATE careers SET trait_weights = '{"aptitude": {"spatial": 0.27, "logical": 0.24, "numerical": 0.23, "verbal": 0.17, "creative": 0.09}, "interest": {"social": 0.63, "investigative": 0.32, "conventional": 0.05}, "cognitive": {"structured": 0.68, "analytical": 0.32}}' WHERE name = 'Nurse';
-- Physiotherapist: O*NET 29-1123.00 Physical Therapists
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.34, "logical": 0.25, "creative": 0.23, "spatial": 0.1, "numerical": 0.08}, "interest": {"social": 0.63, "investigative": 0.32, "artistic": 0.05}, "cognitive": {"analytical": 0.77, "structured": 0.23}}' WHERE name = 'Physiotherapist';
-- Veterinarian: O*NET 29-1131.00 Veterinarians
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.33, "verbal": 0.26, "logical": 0.23, "spatial": 0.12, "creative": 0.06}, "interest": {"investigative": 0.58, "realistic": 0.31, "social": 0.11}, "cognitive": {"analytical": 0.77, "structured": 0.23}}' WHERE name = 'Veterinarian';
-- O*NET has no Ayurveda occupation; Naturopathic Physicians is the closest traditional-medicine practitioner.
-- AYUSH Doctor (BAMS): O*NET 29-1299.01 Naturopathic Physicians
UPDATE careers SET trait_weights = '{"aptitude": {"logical": 0.27, "creative": 0.23, "spatial": 0.2, "verbal": 0.17, "numerical": 0.13}, "interest": {"social": 0.52, "investigative": 0.48}, "cognitive": {"analytical": 0.82, "structured": 0.18}}' WHERE name = 'AYUSH Doctor (BAMS)';
-- Psychologist: O*NET 19-3033.00 Clinical and Counseling Psychologists
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.45, "creative": 0.37, "logical": 0.13, "spatial": 0.05}, "interest": {"social": 0.52, "investigative": 0.32, "artistic": 0.16}, "cognitive": {"analytical": 0.87, "structured": 0.13}}' WHERE name = 'Psychologist';
-- Chartered Accountant (CA): O*NET 13-2011.00 Accountants and Auditors
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.59, "spatial": 0.21, "logical": 0.12, "verbal": 0.07, "creative": 0.01}, "interest": {"conventional": 0.66, "enterprising": 0.28, "investigative": 0.06}, "cognitive": {"analytical": 0.61, "structured": 0.39}}' WHERE name = 'Chartered Accountant (CA)';
-- Company Secretary: O*NET 13-1041.00 Compliance Officers
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.59, "logical": 0.32, "spatial": 0.05, "creative": 0.04}, "interest": {"conventional": 0.58, "enterprising": 0.41, "social": 0.01}, "cognitive": {"structured": 1.0}}' WHERE name = 'Company Secretary';
-- Cost Accountant (CMA): O*NET 13-2031.00 Budget Analysts
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.79, "verbal": 0.1, "logical": 0.09, "creative": 0.02}, "interest": {"conventional": 0.51, "enterprising": 0.42, "investigative": 0.07}, "cognitive": {"analytical": 0.67, "structured": 0.33}}' WHERE name = 'Cost Accountant (CMA)';
-- Financial and Investment Analysts (13-2051.00) has no ability ratings in O*NET 31.0; this is the closest finance occupation that has all three.
-- Investment Banker: O*NET 41-3031.00 Securities, Commodities, and Financial Services Sales Agents
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.56, "creative": 0.21, "verbal": 0.13, "spatial": 0.1}, "interest": {"enterprising": 0.79, "conventional": 0.18, "social": 0.03}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Investment Banker';
-- Financial and Investment Analysts (13-2051.00) has no ability ratings in O*NET 31.0; Credit Analysts is the closest analytical finance occupation that has all three.
-- Financial Analyst: O*NET 13-2041.00 Credit Analysts
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.71, "logical": 0.11, "spatial": 0.1, "verbal": 0.08}, "interest": {"conventional": 0.51, "enterprising": 0.39, "investigative": 0.1}, "cognitive": {"analytical": 0.64, "structured": 0.36}}' WHERE name = 'Financial Analyst';
-- Marketing Manager: O*NET 11-2021.00 Marketing Managers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.48, "numerical": 0.22, "verbal": 0.16, "spatial": 0.1, "logical": 0.04}, "interest": {"enterprising": 0.85, "artistic": 0.11, "conventional": 0.04}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Marketing Manager';
-- HR Manager: O*NET 11-3121.00 Human Resources Managers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.34, "verbal": 0.28, "numerical": 0.15, "logical": 0.12, "spatial": 0.11}, "interest": {"enterprising": 0.68, "conventional": 0.17, "social": 0.15}, "cognitive": {"analytical": 1.0}}' WHERE name = 'HR Manager';
-- Business Analyst: O*NET 13-1111.00 Management Analysts
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.34, "verbal": 0.26, "numerical": 0.19, "logical": 0.16, "spatial": 0.05}, "interest": {"investigative": 0.37, "enterprising": 0.36, "conventional": 0.27}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Business Analyst';
-- Economist: O*NET 19-3011.00 Economists
UPDATE careers SET trait_weights = '{"aptitude": {"numerical": 0.52, "creative": 0.26, "verbal": 0.16, "logical": 0.06}, "interest": {"investigative": 0.7, "enterprising": 0.21, "artistic": 0.09}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Economist';
-- Hospitality Manager: O*NET 11-9081.00 Lodging Managers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.32, "numerical": 0.25, "verbal": 0.21, "spatial": 0.12, "logical": 0.1}, "interest": {"enterprising": 0.62, "social": 0.25, "conventional": 0.13}, "cognitive": {"structured": 0.78, "analytical": 0.22}}' WHERE name = 'Hospitality Manager';
-- UX/UI Designer: O*NET 15-1255.00 Web and Digital Interface Designers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.82, "spatial": 0.18}, "interest": {"artistic": 0.58, "investigative": 0.35, "enterprising": 0.07}, "cognitive": {"analytical": 1.0}}' WHERE name = 'UX/UI Designer';
-- Communication Designer: O*NET 27-1024.00 Graphic Designers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 1.0}, "interest": {"artistic": 0.89, "enterprising": 0.11}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Communication Designer';
-- Fashion Designer: O*NET 27-1022.00 Fashion Designers
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.86, "verbal": 0.1, "logical": 0.04}, "interest": {"artistic": 0.82, "enterprising": 0.18}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Fashion Designer';
-- Animator / VFX Artist: O*NET 27-1014.00 Special Effects Artists and Animators
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.68, "verbal": 0.32}, "interest": {"artistic": 1.0}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Animator / VFX Artist';
-- Journalist: O*NET 27-3023.00 News Analysts, Reporters, and Journalists
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.38, "creative": 0.31, "logical": 0.17, "spatial": 0.14}, "interest": {"artistic": 0.62, "enterprising": 0.22, "investigative": 0.16}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Journalist';
-- Architect: O*NET 17-1011.00 Architects, Except Landscape and Naval
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.3, "logical": 0.2, "numerical": 0.2, "spatial": 0.17, "verbal": 0.13}, "interest": {"artistic": 0.57, "enterprising": 0.21, "investigative": 0.13, "realistic": 0.09}, "cognitive": {"analytical": 0.83, "structured": 0.17}}' WHERE name = 'Architect';
-- Corporate Lawyer: O*NET 23-1011.00 Lawyers
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.39, "creative": 0.32, "logical": 0.2, "spatial": 0.09}, "interest": {"enterprising": 0.57, "investigative": 0.21, "social": 0.11, "artistic": 0.1, "conventional": 0.01}, "cognitive": {"analytical": 0.78, "structured": 0.22}}' WHERE name = 'Corporate Lawyer';
-- Civil Services Officer (IAS / IPS): O*NET 11-1011.00 Chief Executives
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.3, "verbal": 0.23, "numerical": 0.19, "logical": 0.15, "spatial": 0.13}, "interest": {"enterprising": 0.77, "social": 0.11, "conventional": 0.08, "artistic": 0.04}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Civil Services Officer (IAS / IPS)';
-- Policy Analyst: O*NET 19-3094.00 Political Scientists
UPDATE careers SET trait_weights = '{"aptitude": {"verbal": 0.65, "creative": 0.24, "logical": 0.11}, "interest": {"investigative": 0.51, "artistic": 0.3, "enterprising": 0.12, "social": 0.07}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Policy Analyst';
-- Educational Policy Specialist: O*NET 25-9031.00 Instructional Coordinators
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.33, "verbal": 0.25, "logical": 0.17, "numerical": 0.16, "spatial": 0.09}, "interest": {"social": 0.46, "artistic": 0.23, "enterprising": 0.21, "investigative": 0.1}, "cognitive": {"analytical": 1.0}}' WHERE name = 'Educational Policy Specialist';
-- School Teacher: O*NET 25-2031.00 Secondary School Teachers, Except Special and Career/Technical Education
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.35, "verbal": 0.25, "numerical": 0.22, "logical": 0.12, "spatial": 0.06}, "interest": {"social": 0.68, "artistic": 0.31, "enterprising": 0.01}, "cognitive": {"analytical": 1.0}}' WHERE name = 'School Teacher';
-- O*NET has no ratings for military officers; police and detective supervisors are the closest civilian occupation for a disciplined, command-and-field role.
-- Armed Forces Officer (NDA): O*NET 33-1012.00 First-Line Supervisors of Police and Detectives
UPDATE careers SET trait_weights = '{"aptitude": {"spatial": 0.31, "verbal": 0.3, "logical": 0.25, "creative": 0.14}, "interest": {"enterprising": 0.75, "social": 0.15, "conventional": 0.1}, "cognitive": {"structured": 1.0}}' WHERE name = 'Armed Forces Officer (NDA)';
-- Sports & Fitness Professional: O*NET 27-2022.00 Coaches and Scouts
UPDATE careers SET trait_weights = '{"aptitude": {"creative": 0.48, "logical": 0.23, "verbal": 0.18, "spatial": 0.11}, "interest": {"social": 0.45, "enterprising": 0.45, "artistic": 0.1}, "cognitive": {"structured": 0.51, "analytical": 0.49}}' WHERE name = 'Sports & Fitness Professional';
