-- =============================================================================
-- Seed 04: national market data per career, and the national living cost.
--
-- One 'India' row per career (state-level figures aren't published for these occupations, so the backend
-- uses this national row for every state and flags it 'estimated'). Every row is estimated = true, because
-- demand and growth are SECTOR figures standing in for the occupation. Each row's source names all three:
--   salary  PayScale India, occupation page: entry = the "less than 1 year experience" average total pay,
--           median = the average base salary. as_of is that page's "updated" date.
--   demand  ManpowerGroup Employment Outlook Survey, India, Q4 2026 (published 8 Sep 2026): the sector's Net
--           Employment Outlook. Only Finance & Insurance (60) and Information (57) were published;
--           other careers use the national NEO (54).
--   growth  Naukri JobSpeak, August 2026 (published 7 Sep 2026): year-on-year hiring growth for the sector
--           or role. Sectors it didn't report use the overall white-collar growth (14).
-- The NDA officer's pay is the starting pay in UPSC's NDA & NA (II) 2026 notice: Level 10 basic Rs 56,100 +
-- Military Service Pay Rs 15,500 a month = Rs 8,59,200 a year, before allowances.
-- =============================================================================

INSERT INTO market_data
    (career_id, region, entry_salary, median_salary, demand_index, growth_rate, as_of, source, source_url, estimated)
SELECT c.id, 'India', v.entry_salary, v.median_salary, v.demand, v.growth, CAST(v.as_of AS date), v.source, v.url, true
FROM (VALUES
    ('Software Engineer', 537425, 813748, 57, 11, '2026-07-12',
     'Salary: PayScale India, Software Engineer (4,950 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, IT/software services.',
     'https://www.payscale.com/research/IN/Job=Software_Engineer/Salary'),
    ('Data Scientist', 595255, 1017652, 57, 31, '2026-07-09',
     'Salary: PayScale India, Data Scientist (1,267 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, AI/ML roles.',
     'https://www.payscale.com/research/IN/Job=Data_Scientist/Salary'),
    ('Mechanical Engineer', 303575, 516339, 54, 19, '2026-06-13',
     'Salary: PayScale India, Mechanical Engineer (1,403 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, auto sector.',
     'https://www.payscale.com/research/IN/Job=Mechanical_Engineer/Salary'),
    ('Robotics Engineer', 393054, 500198, 54, 19, '2025-06-11',
     'Salary: PayScale India, Robotics Engineer (67 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, auto sector.',
     'https://www.payscale.com/research/IN/Job=Robotics_Engineer/Salary'),
    ('Medical Doctor (MBBS)', 621036, 714892, 54, 16, '2026-03-06',
     'Salary: PayScale India, Physician / Doctor, General Practice (81 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Physician_%2F_Doctor%2C_General_Practice/Salary'),
    ('Biotechnology Researcher', 505652, 610419, 54, 2, '2026-06-16',
     'Salary: PayScale India, Research Scientist, Biotechnology (64 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, pharma/biotech.',
     'https://www.payscale.com/research/IN/Job=Research_Scientist%2C_Biotechnology/Salary'),
    ('Chartered Accountant (CA)', 730413, 1017284, 60, 10, '2026-06-16',
     'Salary: PayScale India, Chartered Accountant (478 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Chartered_Accountant/Salary'),
    ('Investment Banker', 606782, 886080, 60, 10, '2026-03-26',
     'Salary: PayScale India, Investment Banker (51 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Investment_Banker/Salary'),
    ('UX/UI Designer', 400661, 610954, 57, 11, '2026-06-08',
     'Salary: PayScale India, UX Designer (484 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, IT/software services.',
     'https://www.payscale.com/research/IN/Job=UX_Designer/Salary'),
    ('Educational Policy Specialist', 336000, 594952, 54, -8, '2025-04-01',
     'Salary: PayScale India, Policy Analyst (9 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, education.',
     'https://www.payscale.com/research/IN/Job=Policy_Analyst/Salary'),
    ('Agricultural Scientist', 335000, 400756, 54, 14, '2025-08-14',
     'Salary: PayScale India, Agronomist (31 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Agronomist/Salary'),
    ('Corporate Lawyer', 585549, 616736, 54, 14, '2026-03-16',
     'Salary: PayScale India, Corporate Lawyer (56 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Corporate_Lawyer/Salary'),
    ('Armed Forces Officer (NDA)', 859200, 859200, 54, 14, '2026-05-20',
     'Pay: UPSC NDA & NA (II) 2026 notice, Lieutenant Level 10 basic + Military Service Pay, before allowances (used for both figures). Demand and growth: national ManpowerGroup and JobSpeak figures, as no defence figure is published.',
     'https://www.upsc.gov.in/sites/default/files/Notif-NDA-II-2026-Engl-200526.pdf'),
    -- careers added with the stream-aware catalog (same method)
    ('AI / ML Engineer', 596082, 1022861, 57, 31, '2026-07-11',
     'Salary: PayScale India, Machine Learning Engineer (232 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, AI/ML roles.',
     'https://www.payscale.com/research/IN/Job=Machine_Learning_Engineer/Salary'),
    ('Cybersecurity Analyst', 473098, 584251, 57, 11, '2026-05-24',
     'Salary: PayScale India, Cyber Security Analyst (358 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, IT/software services.',
     'https://www.payscale.com/research/IN/Job=Cyber_Security_Analyst/Salary'),
    ('Electronics & Telecom Engineer', 382876, 595976, 57, 14, '2026-01-08',
     'Salary: PayScale India, Electronics Engineer (124 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Electronics_Engineer/Salary'),
    ('VLSI / Chip Design Engineer', 491318, 1542312, 54, 14, '2025-04-20',
     'Salary: PayScale India, ASIC Design Engineer (36 profiles, small sample; there is no India page for VLSI design engineers). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=ASIC_Design_Engineer/Salary'),
    ('Embedded Systems Engineer', 408012, 581811, 54, 14, '2026-06-15',
     'Salary: PayScale India, Embedded Software Engineer (186 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Embedded_Software_Engineer/Salary'),
    ('Electrical Engineer', 307347, 513711, 54, 14, '2026-06-27',
     'Salary: PayScale India, Electrical Engineer (551 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Electrical_Engineer/Salary'),
    ('Instrumentation & Control Engineer', 390385, 710830, 54, 14, '2026-02-07',
     'Salary: PayScale India, Instrumentation Engineer (93 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Instrumentation_Engineer/Salary'),
    ('Automobile / EV Engineer', 491318, 872216, 54, 19, '2025-06-17',
     'Salary: PayScale India, Automotive Engineer (60 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, auto sector.',
     'https://www.payscale.com/research/IN/Job=Automotive_Engineer/Salary'),
    ('Aerospace Engineer', 714095, 709572, 54, 14, '2025-10-17',
     'Salary: PayScale India, Aerospace Engineer (187 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Aerospace_Engineer/Salary'),
    ('Civil Engineer', 248084, 394160, 54, 14, '2026-07-04',
     'Salary: PayScale India, Civil Engineer (953 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Civil_Engineer/Salary'),
    ('Chemical Engineer', 435553, 483599, 54, 14, '2026-04-30',
     'Salary: PayScale India, Chemical Engineer (88 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Chemical_Engineer/Salary'),
    ('Quantitative Analyst', 1140000, 1473953, 60, 10, '2026-04-28',
     'Salary: PayScale India, Quantitative Analyst (21 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Quantitative_Analyst/Salary'),
    ('Astrophysicist / Astronomer', 608205, 820705, 54, 14, '2026-05-20',
     'Salary: PayScale India, Research Scientist (212 profiles; there is no India page for astronomers). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Research_Scientist/Salary'),
    ('Physicist', 575000, 800000, 54, 14, '2025-07-06',
     'Salary: PayScale India, Physicist (35 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Physicist/Salary'),
    ('Mathematician / Statistician', 496372, 550000, 54, 14, '2023-06-13',
     'Salary: PayScale India, Statistician (49 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Statistician/Salary'),
    ('Actuary', 840000, 1017365, 60, 10, '2026-04-08',
     'Salary: PayScale India, Actuary (26 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Actuary/Salary'),
    ('Microbiologist', 308652, 368551, 54, 2, '2026-05-16',
     'Salary: PayScale India, Microbiologist (91 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, pharma/biotech.',
     'https://www.payscale.com/research/IN/Job=Microbiologist/Salary'),
    ('Forensic Scientist', 404521, 350000, 54, 14, '2026-02-11',
     'Salary: PayScale India, Forensic Scientist (37 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Forensic_Scientist/Salary'),
    ('Environmental Scientist', 400000, 790957, 54, 14, '2024-11-12',
     'Salary: PayScale India, Environmental Scientist (15 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Environmental_Scientist/Salary'),
    ('Dentist', 303464, 400000, 54, 16, '2026-05-21',
     'Salary: PayScale India, Dentist (103 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Dentist/Salary'),
    ('Pharmacist', 251181, 300140, 54, 2, '2026-06-18',
     'Salary: PayScale India, Pharmacist (371 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, pharma/biotech.',
     'https://www.payscale.com/research/IN/Job=Pharmacist/Salary'),
    ('Nurse', 229674, 307703, 54, 16, '2026-02-27',
     'Salary: PayScale India, Staff Nurse (278 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Staff_Nurse/Salary'),
    ('Physiotherapist', 292986, 320000, 54, 16, '2026-07-10',
     'Salary: PayScale India, Physiotherapist (201 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Physiotherapist/Salary'),
    ('Veterinarian', 580638, 786123, 54, 14, '2025-04-17',
     'Salary: PayScale India, Veterinarian (43 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Veterinarian/Salary'),
    ('AYUSH Doctor (BAMS)', 584274, 610419, 54, 16, '2025-06-13',
     'Salary: PayScale India, Medical Officer (127 profiles; there is no India page for Ayurvedic doctors). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Medical_Officer/Salary'),
    ('Psychologist', 480325, 455276, 54, 16, '2026-05-29',
     'Salary: PayScale India, Clinical Psychologist (98 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, healthcare.',
     'https://www.payscale.com/research/IN/Job=Clinical_Psychologist/Salary'),
    ('Company Secretary', 457825, 618247, 60, 10, '2025-02-19',
     'Salary: PayScale India, Corporate Secretary (118 profiles; there is no India page titled Company Secretary). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Corporate_Secretary/Salary'),
    ('Cost Accountant (CMA)', 501390, 596437, 60, 10, '2026-02-12',
     'Salary: PayScale India, Cost Accountant (54 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Cost_Accountant/Salary'),
    ('Financial Analyst', 388390, 571613, 60, 10, '2026-07-10',
     'Salary: PayScale India, Financial Analyst (1,058 profiles). Demand: ManpowerGroup MEOS India Q4 2026, Finance & Insurance. Growth: Naukri JobSpeak Aug 2026, banking/financial services.',
     'https://www.payscale.com/research/IN/Job=Financial_Analyst/Salary'),
    ('Marketing Manager', 464010, 865044, 54, 14, '2026-07-08',
     'Salary: PayScale India, Marketing Manager (746 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Marketing_Manager/Salary'),
    ('HR Manager', 390764, 848380, 54, 14, '2026-07-01',
     'Salary: PayScale India, Human Resources (HR) Manager (1,212 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Human_Resources_(HR)_Manager/Salary'),
    ('Business Analyst', 516542, 688693, 54, 14, '2026-04-21',
     'Salary: PayScale India, Business Analyst (381 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Business_Analyst_(Unspecified_Type)/Salary'),
    ('Economist', 499991, 650000, 54, 14, '2025-08-09',
     'Salary: PayScale India, Economist (34 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Economist/Salary'),
    ('Hospitality Manager', 459496, 500000, 54, 14, '2026-05-08',
     'Salary: PayScale India, Hotel Manager (37 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Hotel_Manager/Salary'),
    ('Communication Designer', 241372, 364761, 54, 14, '2026-07-02',
     'Salary: PayScale India, Graphic Designer (987 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Graphic_Designer/Salary'),
    ('Fashion Designer', 301590, 400832, 54, 14, '2025-08-12',
     'Salary: PayScale India, Fashion Designer (207 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Fashion_Designer/Salary'),
    ('Animator / VFX Artist', 304413, 395479, 57, 14, '2025-06-28',
     'Salary: PayScale India, Animator (52 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Animator/Salary'),
    ('Journalist', 361885, 382380, 57, 14, '2025-07-26',
     'Salary: PayScale India, Journalist (59 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, Information sector. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Journalist/Salary'),
    ('Architect', 238367, 519678, 54, 14, '2026-02-24',
     'Salary: PayScale India, Project Architect (85 profiles; the general Architect page has no India data). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Project_Architect/Salary'),
    ('Policy Analyst', 336000, 594952, 54, 14, '2025-04-01',
     'Salary: PayScale India, Policy Analyst (9 profiles, small sample). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Policy_Analyst/Salary'),
    ('School Teacher', 297059, 364776, 54, -8, '2026-05-30',
     'Salary: PayScale India, High School Teacher (328 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, education.',
     'https://www.payscale.com/research/IN/Job=High_School_Teacher/Salary'),
    ('Sports & Fitness Professional', 380000, 480478, 54, 14, '2025-01-16',
     'Salary: PayScale India, Physical Education Teacher (83 profiles). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.payscale.com/research/IN/Job=Physical_Education_Teacher/Salary'),
    ('Civil Services Officer (IAS / IPS)', 673200, 673200, 54, 14, '2026-05-20',
     'Pay: 7th CPC pay matrix Level 10, the entry level for IAS and IPS officers: basic Rs 56,100 a month = Rs 6,73,200 a year, before allowances (the same Level 10 basic as in the UPSC NDA & NA (II) 2026 notice). Demand: ManpowerGroup MEOS India Q4 2026, national. Growth: Naukri JobSpeak Aug 2026, overall (sector not reported).',
     'https://www.upsc.gov.in/sites/default/files/Notif-NDA-II-2026-Engl-200526.pdf')
) AS v(career, entry_salary, median_salary, demand, growth, as_of, source, url)
JOIN careers c ON c.name = v.career
ON CONFLICT (career_id, region, as_of) DO UPDATE SET
    entry_salary  = EXCLUDED.entry_salary,
    median_salary = EXCLUDED.median_salary,
    demand_index  = EXCLUDED.demand_index,
    growth_rate   = EXCLUDED.growth_rate,
    source        = EXCLUDED.source,
    source_url    = EXCLUDED.source_url,
    estimated     = EXCLUDED.estimated;

-- Living cost: average monthly per-capita consumption in urban India, Household Consumption Expenditure
-- Survey 2023-24 (MoSPI press note, 27 Dec 2024). Used for living costs while studying (when a college's
-- hostel and mess cost isn't known) and after graduation (break-even). It's a per-person household average,
-- so a single person living alone in a big city will usually spend more.
INSERT INTO regions (name, monthly_living_cost, source, source_url, as_of, estimated) VALUES
    ('India', 6996, 'MoSPI, Household Consumption Expenditure Survey 2023-24: average urban MPCE',
     'https://www.mospi.gov.in/sites/default/files/press_release/HCES_Press_Note_2023-24_27122024_rev.pdf',
     DATE '2024-12-27', false)
ON CONFLICT (name) DO UPDATE SET
    monthly_living_cost = EXCLUDED.monthly_living_cost,
    source              = EXCLUDED.source,
    source_url          = EXCLUDED.source_url,
    as_of               = EXCLUDED.as_of,
    estimated           = EXCLUDED.estimated;
