-- =============================================================================
-- Seed 05: scholarships whose rules the app can check from a family's profile.
--
-- Left out on purpose: schemes whose main rule can't be checked from the profile (INSPIRE-SHE's "top 1% of
-- your board") and schemes without a fixed amount (post-matric scholarships that reimburse fees).
-- A deadline is filled in only when a published source gives it.
-- =============================================================================

INSERT INTO scholarships
    (name, provider, amount, amount_period, deadline, income_limit, categories, states, min_percentage, gender,
     course_level, eligibility_text, source, source_url, as_of, estimated)
VALUES
    ('Central Sector Scheme of Scholarship for College and University Students', 'Ministry of Education',
     12000, 'per_year', NULL, 450000, '{}', '{}', NULL, NULL, 'UG',
     'Family income up to Rs 4.5 lakh a year and marks above the 80th percentile of your Class 12 board (in your '
     'stream), in a regular degree course. Rs 12,000 a year at graduation level (Rs 20,000 at postgraduate level); '
     'up to 82,000 new awards a year. Apply on the National Scholarship Portal.',
     'Ministry of Education, Central Sector Scheme of Scholarship', 'https://www.education.gov.in/node/255',
     DATE '2026-10-07', false),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'AICTE',
     50000, 'per_year', NULL, 800000, '{}', '{}', NULL, 'female', 'UG',
     'For girls admitted to the first year of an AICTE-approved technical degree (such as B.Tech), with family income '
     'up to Rs 8 lakh a year; selected on Class 12 marks. Rs 50,000 a year for up to 4 years. Apply on the National '
     'Scholarship Portal.',
     'AICTE Pragati scheme page (2026-27 notification) and Thapar Institute''s 2026-27 notice',
     'https://www.aicte.gov.in/schemes/students-development-schemes/Pragati/General-Instructions',
     DATE '2026-10-07', false),
    ('Kotak Kanya Scholarship', 'Kotak Education Foundation',
     150000, 'per_year', DATE '2026-09-30', 600000, '{}', '{}', 75, 'female', 'UG',
     'For girls with at least 75% in Class 12 and family income up to Rs 6 lakh a year, in the first year of a '
     'professional degree (engineering, MBBS, architecture, design, integrated LLB and more) at an NIRF- or '
     'NAAC-accredited institute. Rs 1.5 lakh a year until graduation; 500 new scholars for 2026-27.',
     'Kotak Kanya Scholarship 2026-27, as reported by India CSR (Jul 2026)',
     'https://indiacsr.in/kotak-kanya-scholarship-2026-500-girls-to-receive-rs-1-5-lakh-annually/',
     DATE '2026-07-28', false)
ON CONFLICT (name) DO UPDATE SET
    provider = EXCLUDED.provider, amount = EXCLUDED.amount, amount_period = EXCLUDED.amount_period,
    deadline = EXCLUDED.deadline, income_limit = EXCLUDED.income_limit, categories = EXCLUDED.categories,
    states = EXCLUDED.states, min_percentage = EXCLUDED.min_percentage, gender = EXCLUDED.gender,
    course_level = EXCLUDED.course_level, eligibility_text = EXCLUDED.eligibility_text, source = EXCLUDED.source,
    source_url = EXCLUDED.source_url, as_of = EXCLUDED.as_of, estimated = EXCLUDED.estimated;

-- Which careers each scholarship applies to (the courses it covers).
INSERT INTO scholarship_careers (scholarship_id, career_id)
SELECT s.id, c.id
FROM (VALUES
    -- any regular degree course (every career except NDA, where the Government pays)
    ('Central Sector Scheme of Scholarship for College and University Students', 'Software Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Data Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'AI / ML Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Cybersecurity Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Electronics & Telecom Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'VLSI / Chip Design Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Embedded Systems Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Electrical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Instrumentation & Control Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Mechanical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Robotics Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Automobile / EV Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Aerospace Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Civil Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Chemical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Quantitative Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Astrophysicist / Astronomer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Physicist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Mathematician / Statistician'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Actuary'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Biotechnology Researcher'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Microbiologist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Agricultural Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Forensic Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Environmental Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Medical Doctor (MBBS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Dentist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Pharmacist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Nurse'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Physiotherapist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Veterinarian'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'AYUSH Doctor (BAMS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Psychologist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Chartered Accountant (CA)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Company Secretary'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Cost Accountant (CMA)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Investment Banker'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Financial Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Marketing Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'HR Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Business Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Economist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Hospitality Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'UX/UI Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Communication Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Fashion Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Animator / VFX Artist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Journalist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Architect'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Corporate Lawyer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Civil Services Officer (IAS / IPS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Policy Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Educational Policy Specialist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'School Teacher'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Sports & Fitness Professional'),
    -- AICTE-approved technical degrees (B.Tech / B.E.)
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Software Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Data Scientist'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'AI / ML Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Cybersecurity Analyst'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Electronics & Telecom Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'VLSI / Chip Design Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Embedded Systems Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Electrical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Instrumentation & Control Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Mechanical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Robotics Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Automobile / EV Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Aerospace Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Civil Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Chemical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Quantitative Analyst'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Astrophysicist / Astronomer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Physicist'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Mathematician / Statistician'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Biotechnology Researcher'),
    -- professional degrees: engineering, MBBS, architecture, design, integrated LLB
    ('Kotak Kanya Scholarship', 'Software Engineer'),
    ('Kotak Kanya Scholarship', 'Data Scientist'),
    ('Kotak Kanya Scholarship', 'AI / ML Engineer'),
    ('Kotak Kanya Scholarship', 'Cybersecurity Analyst'),
    ('Kotak Kanya Scholarship', 'Electronics & Telecom Engineer'),
    ('Kotak Kanya Scholarship', 'VLSI / Chip Design Engineer'),
    ('Kotak Kanya Scholarship', 'Embedded Systems Engineer'),
    ('Kotak Kanya Scholarship', 'Electrical Engineer'),
    ('Kotak Kanya Scholarship', 'Instrumentation & Control Engineer'),
    ('Kotak Kanya Scholarship', 'Mechanical Engineer'),
    ('Kotak Kanya Scholarship', 'Robotics Engineer'),
    ('Kotak Kanya Scholarship', 'Automobile / EV Engineer'),
    ('Kotak Kanya Scholarship', 'Aerospace Engineer'),
    ('Kotak Kanya Scholarship', 'Civil Engineer'),
    ('Kotak Kanya Scholarship', 'Chemical Engineer'),
    ('Kotak Kanya Scholarship', 'Quantitative Analyst'),
    ('Kotak Kanya Scholarship', 'Astrophysicist / Astronomer'),
    ('Kotak Kanya Scholarship', 'Physicist'),
    ('Kotak Kanya Scholarship', 'Mathematician / Statistician'),
    ('Kotak Kanya Scholarship', 'Biotechnology Researcher'),
    ('Kotak Kanya Scholarship', 'Medical Doctor (MBBS)'),
    ('Kotak Kanya Scholarship', 'UX/UI Designer'),
    ('Kotak Kanya Scholarship', 'Communication Designer'),
    ('Kotak Kanya Scholarship', 'Fashion Designer'),
    ('Kotak Kanya Scholarship', 'Animator / VFX Artist'),
    ('Kotak Kanya Scholarship', 'Architect'),
    ('Kotak Kanya Scholarship', 'Corporate Lawyer')
) AS v(scholarship, career)
JOIN scholarships s ON s.name = v.scholarship
JOIN careers c ON c.name = v.career
ON CONFLICT DO NOTHING;

-- Links the list above no longer has.
DELETE FROM scholarship_careers sc
USING scholarships s, careers c
WHERE s.id = sc.scholarship_id AND c.id = sc.career_id AND (s.name, c.name) NOT IN (VALUES
    ('Central Sector Scheme of Scholarship for College and University Students', 'Software Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Data Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'AI / ML Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Cybersecurity Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Electronics & Telecom Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'VLSI / Chip Design Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Embedded Systems Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Electrical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Instrumentation & Control Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Mechanical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Robotics Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Automobile / EV Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Aerospace Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Civil Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Chemical Engineer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Quantitative Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Astrophysicist / Astronomer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Physicist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Mathematician / Statistician'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Actuary'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Biotechnology Researcher'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Microbiologist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Agricultural Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Forensic Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Environmental Scientist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Medical Doctor (MBBS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Dentist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Pharmacist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Nurse'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Physiotherapist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Veterinarian'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'AYUSH Doctor (BAMS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Psychologist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Chartered Accountant (CA)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Company Secretary'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Cost Accountant (CMA)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Investment Banker'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Financial Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Marketing Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'HR Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Business Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Economist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Hospitality Manager'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'UX/UI Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Communication Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Fashion Designer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Animator / VFX Artist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Journalist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Architect'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Corporate Lawyer'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Civil Services Officer (IAS / IPS)'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Policy Analyst'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Educational Policy Specialist'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'School Teacher'),
    ('Central Sector Scheme of Scholarship for College and University Students', 'Sports & Fitness Professional'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Software Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Data Scientist'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'AI / ML Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Cybersecurity Analyst'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Electronics & Telecom Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'VLSI / Chip Design Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Embedded Systems Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Electrical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Instrumentation & Control Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Mechanical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Robotics Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Automobile / EV Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Aerospace Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Civil Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Chemical Engineer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Quantitative Analyst'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Astrophysicist / Astronomer'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Physicist'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Mathematician / Statistician'),
    ('AICTE Pragati Scholarship for Girls (Degree)', 'Biotechnology Researcher'),
    ('Kotak Kanya Scholarship', 'Software Engineer'),
    ('Kotak Kanya Scholarship', 'Data Scientist'),
    ('Kotak Kanya Scholarship', 'AI / ML Engineer'),
    ('Kotak Kanya Scholarship', 'Cybersecurity Analyst'),
    ('Kotak Kanya Scholarship', 'Electronics & Telecom Engineer'),
    ('Kotak Kanya Scholarship', 'VLSI / Chip Design Engineer'),
    ('Kotak Kanya Scholarship', 'Embedded Systems Engineer'),
    ('Kotak Kanya Scholarship', 'Electrical Engineer'),
    ('Kotak Kanya Scholarship', 'Instrumentation & Control Engineer'),
    ('Kotak Kanya Scholarship', 'Mechanical Engineer'),
    ('Kotak Kanya Scholarship', 'Robotics Engineer'),
    ('Kotak Kanya Scholarship', 'Automobile / EV Engineer'),
    ('Kotak Kanya Scholarship', 'Aerospace Engineer'),
    ('Kotak Kanya Scholarship', 'Civil Engineer'),
    ('Kotak Kanya Scholarship', 'Chemical Engineer'),
    ('Kotak Kanya Scholarship', 'Quantitative Analyst'),
    ('Kotak Kanya Scholarship', 'Astrophysicist / Astronomer'),
    ('Kotak Kanya Scholarship', 'Physicist'),
    ('Kotak Kanya Scholarship', 'Mathematician / Statistician'),
    ('Kotak Kanya Scholarship', 'Biotechnology Researcher'),
    ('Kotak Kanya Scholarship', 'Medical Doctor (MBBS)'),
    ('Kotak Kanya Scholarship', 'UX/UI Designer'),
    ('Kotak Kanya Scholarship', 'Communication Designer'),
    ('Kotak Kanya Scholarship', 'Fashion Designer'),
    ('Kotak Kanya Scholarship', 'Animator / VFX Artist'),
    ('Kotak Kanya Scholarship', 'Architect'),
    ('Kotak Kanya Scholarship', 'Corporate Lawyer')
);
